### PR TITLE
Fe user profile styling

### PR DESCRIPTION
**Pull request by Menubrea**
## Changelog
- Added custom scss folder for profile
- changed ``stylesheet``  in ``head`` to use ``profile/index.scss``, importing global settings from ``root scss index.``
- Configured files for temporary dummy data view. 
- Added dummy data to ``renderUserDetails()``
- Added ``js`` for ``skills[]``, including classes to match hi-fi preview.
- Styled ``HTML`` and ``js`` classes to match current hi-fi preview.

## Updates
- More detailed work on tab styling.

#### Comments
**Do not merge or delete branch**, but setting up PR for you to look at your convenience. It's not final, but shouldn't be that far off from the final product, bar ``code-cleanup``.

## Image preview
Screenshot 2023-01-17 at 19 38 27

### CODE REVIEW

**Comment by Menubrea** [comment]
Screenshot 2023-01-17 at 19 38 27

**Comment by Pjatte1337** [comment]
Looks very god!

**Comment by Pjatte1337** [comment]
Let me know if you want me to merge and delete branch @Menubrea

**Comment by Christonn93** [comment]
> Let me know if you want me to merge and delete branch @Menubrea

just merge it

**Pull request merged**
