### PR TITLE
New PR main to my branch

### PR DESCRIPTION
**Pull request by kardokiyani**
New PR, main to my own branch FE-offers-student-offer.

### CODE REVIEW

**Comment by Christonn93** [comment]
To resolve the conflict add this in your branch `index.scss` file, 
```scss
// Colors and fonts
@import './custom/themeColorVariables';
@import './custom/typography';

// Header and footer
@import './custom/header';
@import './custom/footer';

// Pages
@import './custom/index';

// Bootstrap from module
@import '../../node_modules/bootstrap/scss/bootstrap';
```
commit it and see if that resolves the issue

**Comment by kardokiyani** [comment]
> To resolve the conflict add this in your branch `index.scss` file,
> 
> ```css-scss
> // Colors and fonts
> @import './custom/themeColorVariables';
> @import './custom/typography';
> 
> // Header and footer
> @import './custom/header';
> @import './custom/footer';
> 
> // Pages
> @import './custom/index';
> 
> // Bootstrap from module
> @import '../../node_modules/bootstrap/scss/bootstrap';
> ```
> 
> commit it and see if that resolves the issue

Yeah, so i have some of it, but some of it i had commented out, im gonna make the change and commit, thanks!

**Comment by NeNorvalls** [comment]
Ok!

**Review by NeNorvalls — APPROVED** [review]

**Comment by kardokiyani** [comment]
Did the changes, i don`t know why it says still conflicts.

**Comment by kardokiyani** [comment]
Thanks Christopher for the help, it worked, also thanks Neno for the review.

**Review by NeNorvalls — APPROVED** [review]

**Comment by Fermain** [comment]
Conflicts still need resolution here, @Christonn93 has provided a solution

**Review by NeNorvalls — APPROVED** [review]
Nice job!

**Comment by Christonn93** [comment]
@kardokiyani 
You need to update your work branch from your team branch, if the team branch is not updated you can request a merge from main.

This should resolve the conflict you are having. We can't approve the request before the conflict have been resolves.

**Comment by NeNorvalls** [comment]
Well-done!

**Pull request merged**
