### PR TITLE
Revert "Refactor API Integration for User and Listing Management"

### PR DESCRIPTION
**Pull request by ESPR07**
Reverts NoroffFEU/agency.noroff.dev#675

### CODE REVIEW

**Review by AdrianMikk — APPROVED** [review]
Revert needed

**Comment by ESPR07** [comment]
We just had to revert to get the correct functional merge into main

**Comment by AdrianMikk** [comment]
[heart]         Adrian Mikkelsen Johannessen reacted to your message:
________________________________

**Comment by AdrianMikk** [comment]
[like]  Adrian Mikkelsen Johannessen reacted to your message:
________________________________

**Pull request merged**
