### PR TITLE
Fe offers

### PR DESCRIPTION
**Pull request by kardokiyani**
Merging from FE-offers to my branch FE-offers-student-offer.

### CODE REVIEW

**Review by NeNorvalls — APPROVED** [review]
The forms have no validation applied yet? And the navigation is not going anywhere when it is clicked, css for hover or active page.

**Comment by ShaindalDev** [comment]
The custom css should not be put into the index.scss file. It should be put into a custom file instead that then is linked in the index.scss file

**Comment by NeNorvalls** [comment]
Solved the branch conflict first .

**Review by NeNorvalls — COMMENTED** [review]
There is a conflict to be resolve first

**Comment by kardokiyani** [comment]
> The custom css should not be put into the index.scss file. It should be put into a custom file instead that then is linked in the index.scss file

So i move all the custom css into a new css file, and then export import to the index.scss?

**Comment by ShaindalDev** [comment]
Im closing this PR without doing merge, then im making a new PR so that the task branch will get updated from team branch.

**Comment by kardokiyani** [comment]
> Im closing this PR without doing merge, then im making a new PR so that the task branch will get updated from team branch.

Okay thats good, thanks!

**Pull request closed without merging**
