### PR TITLE
Created bootstrap modal for Reject button

### PR DESCRIPTION
**Pull request by dvergnir**
Built modal to pop on clicking the "Reject" button. Styled per Figma.
NB!
I added ```
 data-bs-dismiss="modal"``` to the reject button, so there will be a merge conflict with the previous button styling branch.

### CODE REVIEW

**Comment by dvergnir** [comment]
> I believe a simple rebase can do the trick about the conflicts in the branches, should I do it or do you guys want to keep it in the team? @dvergnir 😊

@martinthoresen do you wish to do this?

**Comment by Fermain** [comment]
This conflict can be solved quite easily using a manual resolution.

**Comment by martinthoresen** [comment]
> > I believe a simple rebase can do the trick about the conflicts in the branches, should I do it or do you guys want to keep it in the team? @dvergnir 😊
> 
> @martinthoresen do you wish to do this?

Sure!

**Comment by martinthoresen** [comment]
Resolved merge conflict manually, and everything loooks ok!

**Review by martinthoresen — APPROVED** [review]

**Review by roxannefranco — APPROVED** [review]
Looking good with no conflicts! :+1:

**Comment by dvergnir** [comment]
> Resolved merge conflict manually, and everything looks ok!

Great job!

**Pull request merged**
