### PR TITLE
create an api call for postApplication.js, where a user can apply to …

### PR DESCRIPTION
**Pull request by Enirose**
Create an api function for postApplication

### CODE REVIEW

**Comment by roxannefranco** [comment]
What is the structure of the object returned?

**Comment by Enirose** [comment]
> What is the structure of the object returned?

You can use "id" and try adding "email".

**Comment by roxannefranco** [comment]
Can you double check this code? It seems incomplete, was it working before you put it up for review?

**Comment by Enirose** [comment]
Hey Rox, im not really sure why. But i'll create a new branch instead. would that be ok?

**Pull request closed without merging**
