### PR TITLE
Delete edit listning

### PR DESCRIPTION
**Pull request by Gonlonge**
added function for edit and delete. Waiting for API endpoint

### CODE REVIEW

**Review by Jenfer93 — COMMENTED** [review]
This looks good! I feel like there might be missing one thing, like the listener for the form, the change of the inputs etc, or am I wrong here? :)

**Comment by Gonlonge** [comment]
I will take a look at it 😄

**Review by akeek — COMMENTED** [review]
Am I mistaken if I say that this is the same as PR #102 ?
If this is the same, then you can close this PR.

**Review by akeek — COMMENTED** [review]
This is pretty much the same as PR #102 if I'm not mistaken? #102 covers this an then some, right? If so, you can just close this PR. Dont merge.

**Review by Jenfer93 — COMMENTED** [review]
Great! Thank you so much, this should be ready to merge as soon as Åke has done his tests again and they are ok! Good job :)

**Comment by Gonlonge** [comment]
Good keep me updated 👍

**Review by akeek — APPROVED** [review]
This was a really clever and good way of solving the task!

**Comment by Gonlonge** [comment]
thank you 😃

**Comment by Gonlonge** [comment]
test OK.

**Pull request merged**
