### PR TITLE
Fixed bug issue with view listing btn

### PR DESCRIPTION
**Pull request by maleneivy**
now redirecting to correct page when user is logged in and not. 
 The issue was that storage was not instantiated.

### CODE REVIEW

**Comment by AdrianMikk** [comment]
I can't seem to get myself logged in, please double-check your code.

**Comment by AdrianMikk** [comment]
I read wrong, but still have to wait for the login to get fixed first

**Review by AdrianMikk — APPROVED** [review]
The view listing button on the home page is now working! Good job

**Comment by maleneivy** [comment]
New PR on this: https://github.com/NoroffFEU/agency.noroff.dev/pull/550

**Pull request merged**
