### PR TITLE
#757 edit listing function

### PR DESCRIPTION
**Pull request by elli95**
## Title
[#757 edit listing function](https://github.com/orgs/NoroffFEU/projects/6/views/31?filterQuery=&pane=issue&itemId=49920373&sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=27576340)

## Describe your changes: 
- I changed the input name values to match the [api documentation](https://agency-api.noroff.dev/api-docs/#/Listings/put_listings__id_)
- Moved the edit listing forum into a modal at "pages/listings/listing/index.html".
- Added a function to displays the listings current values on opening.
- And added a success message, when successfully editing a post.
- Rewrote the PUT request in editSingleListing.js, it shuld work now.

## Type of changes:
- Changed code in html file
- Moved html code to the correct file
- Added new function
- Added new/necessary modals
- Edited/fixed js code
​
## Checklist before requesting a review

* [x] I created a new branch before starting with this ticket?
* [x] I commented the issue after finish in the Frontend Team Board?
* [x] I moved the card to Quality Assurance after finish?

## Did you run into any issues?
- Yes, I encountered issues.

I had some problems with the PUT request.
I got various errors, including:

> "Error: TypeError: Window.fetch: Cannot convert value in record<ByteString, ByteString> branch of (sequence<sequence<ByteString>> or record<ByteString, ByteString>) to ByteString because the character at index 483 has value 8217 which is greater than 255."

Fixed the problem by rewriting the code for the PUT request.
Otherwise, I was not that familiar with the code and spent a little more time familiarise with it.

## Screenshots:
- No screenshots to include.

## Feedback
- Yes, I want feedback.

### CODE REVIEW

**Review by Olekrr — CHANGES_REQUESTED** [review]
Refer to chat in team holmenhollen for requested changes :)

**Comment by Olekrr** [comment]
@kyrregjerstad I have done a small update to this PR which brings changes to the unit test so we can move forward with Elise's changes. If you as part of the testing team wants to review them, or forward it to your teams QA so you are kept in the loop that would be appreciated.

**Comment by kyrregjerstad** [comment]
@Olekrr Cool, looks all good to me! If QA master @Sovak3441 could have a look, that would be great too 👀

**Review by Olekrr — APPROVED** [review]

**Comment by Olekrr** [comment]
Merging this now, with @kyrregjerstad approval on the test. 
We need this to keep working on our tasks - cant wait any longer.

**Pull request merged**
