### PR TITLE
Refactor singleApplicationTemplate to Use Actual API

### PR DESCRIPTION
**Pull request by RamtinMoshtagh**
- Updated `singleApplicationTemplate` function to fetch application data from the actual API.
- Replaced dummy API URL with `apiUrl` and `applicationUrl` from constants for dynamic endpoint construction.
- Added error handling for unsuccessful API responses.
- Function now properly takes `id` as an argument to fetch specific application data.

This commit aligns the function with our actual API's structure, enhancing its functionality and reliability.

### CODE REVIEW

**Review by ESPR07 — APPROVED** [review]

**Comment by kimrm** [comment]
Looks like this PR is breaking the deployment build.

**Comment by RamtinMoshtagh** [comment]
> Looks like this PR is breaking the deployment build.
@kimrm 
issue #591 needs to be merged and updated to the server so that issue #689 can work, and then it wont break the build. Its regarding the applicationURL in constants.js, this has been implemented and changed in #591 because all the api urls where based on dummy Api. Just giving a status :D

**Comment by kimrm** [comment]
Great! thanks :)

**Comment by RamtinMoshtagh** [comment]
> Great! thanks :)
@kimrm
Its working now :)

**Pull request merged**
