### PR TITLE
#487 Fixed email still being stored when "remember me" is unchecked

### PR DESCRIPTION
**Pull request by Ninuskaninus**
In src/js/api/application/auth/login

I changed line 66 from:
        new Store('email', email, false);
To:
        new Store('email', email, Boolean(remember !== 'on'));

to make sure that it checks if the remember-check is true or false before storing the email.

### CODE REVIEW

**Review by KevinHavn — CHANGES_REQUESTED** [review]
This change seems to have created unintended issues - no information is saved to localStorage when "Remember me" is unchecked - leading to information utilizing localStorage such as the user information displaying as undefined on the profile page. 

Let me know if this is only on my end!

**Comment by Ninuskaninus** [comment]
Changed the code again. Still issues with local storage, but the issue is:
"Email address is stored in local storage if user logs in with "Remember me" unchecked."
And the expected outcome is:
"Expected outcome of this is the email address being stored in session storage if "Remember me" is unchecked during login."

Now everything is stored in "session storage" and not "local storage" if the "remember me" is unchecked, but the user index.html still displays undefined...

**Comment by MHerholdt94** [comment]
Hello!

Regarding data being stored in local storage if "remember me" is checked, I believe this wouldn't be an issue after PR #489 is merged. It makes it so data is fetched from either local storage or session storage (depending on "remember me" state on login).

Hope this helps!

**Comment by Ninuskaninus** [comment]
Thank you! That helps alot :)

**Review by KevinHavn — APPROVED** [review]
Lgtm!

**Comment by Olekrr** [comment]
I noticed this PR has not been merged yet even though the changes has been approved.
I'm assuming this is due to the merge conflicts. If you are unfamiliar with merge conflicts, there's a section about it in the "Workflow" course, module 1 - Git Command Line

**Comment by Olekrr** [comment]
Closing pull requests from sprint 1 as part of sprint 2 cleanup - contact me if you want it re-opened

**Pull request closed without merging**
