### PR TITLE
Changed script and link across pages

### PR DESCRIPTION
**Pull request by CamillaHorneland**
Changed loading of scrips and links across pages to make it consistent. But some of the code broke when doing this. e.g. changing li in nav elements and opening menu. So I also loadet <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script> and this fixed it.

### CODE REVIEW

**Review by Emilyrf — CHANGES_REQUESTED** [review]
Hi @CamillaHorneland,

Thanks for your pull request.
However, there is a conflict that needs to be resolved first.
Can you check it?

Captura de Tela 2023-10-06 às 09 43 42
Captura de Tela 2023-10-06 às 09 43 11

**Comment by CamillaHorneland** [comment]
I hope I resolved it now.

**Review by Emilyrf — CHANGES_REQUESTED** [review]
Hey @CamillaHorneland,

Consistency and uniformity is essencial for the application success, thank you for taking care of it, all pages seems to be correctly linked.

I would like to ask for you insight in two of the pages.

- First **pages/admin/index.html**:
Captura de Tela 2023-10-06 às 14 39 23
I am confident this commented out link won't be necessary in the future, maybe just delete it to make the code cleaner?

- Secondly, on  **pages/TBD/apply/index.html** we have a commented out link for  _Fonts awesome._
Captura de Tela 2023-10-06 às 14 50 23
by "uncommenting" it a X button appear on the form: 
Captura de Tela 2023-10-06 às 14 52 19
I am not sure if this button will have a function on the future, should we leave it "unncomented" like it was on the main branch?

**Comment by jkjode** [comment]
>   by "uncommenting" it a X button appear on the form:
>   Captura de Tela 2023-10-06 às 14 52 19
>   I am not sure if this button will have a function on the future, should we leave it "unncomented" like it was on the main branch?

Perhaps best to uncomment the code, but then add a comment in the code and raise question towards it within the code. As to acknowledge the presence of a potential error/issue. This way it is declared for future work.

**Review by Emilyrf — APPROVED** [review]
Hey,

Thank you for the changes.

**Pull request merged**
