### PR TITLE
Search bar on listings page

### PR DESCRIPTION
**Pull request by kmcarlson**
I have removed the border, removed the placeholder text, put the text centered but have not been able to fix it so that the field is larger.

Many someone can field to larger ?

### CODE REVIEW

**Review by karolina-szymanska — APPROVED** [review]
Well done!

**Comment by DarioDeLaFuente** [comment]
@karolina-szymanska Have u revue this cod?
@kmcarlson i you add: w-100 to the  <div class="mt-5 w-100"> like this:
Screenshot 2023-10-15 at 22 02 24
you will get the full weight of the bar. 
like this:
Screenshot 2023-10-15 at 21 42 09

**Comment by kmcarlson** [comment]
thanks for reply, tried to add it as a class. But test again and I'll report back to you both

**Comment by kmcarlson** [comment]
@Bjonne696 
Maybe we should close this one, so rather create a new one, so that we avoid a lot of conflicts

**Pull request closed without merging**
