### PR TITLE
Changed src and added styling

### PR DESCRIPTION
**Pull request by Queenen**
By changing the img src the logo is now visible in both live-server and vite.
I also did some styling in order for the logo to get a proper size.

### CODE REVIEW

**Comment by KristianNilsenAug22FT** [comment]
Perfect. Logo now visible. However not sure the styling is necessary? There is already styling for it in a custom scss file.

the file "https://agency.noroff.dev/src/scss/custom/_header.scss" har this styling for the logo:

.logo-noroff {
  width: 40px;
  height: 56px;
}

I can't find any scenarios where the scss styling doesn't work

**Comment by Queenen** [comment]
> Perfect. Logo now visible. However not sure the styling is necessary? There is already styling for it in a custom scss file.
> 
> the file "https://agency.noroff.dev/src/scss/custom/_header.scss" har this styling for the logo:
> 
> .logo-noroff { width: 40px; height: 56px; }
> 
> I can't find any scenarios where the scss styling doesn't work

Hmm... After changing the src the logo became bigger than before, but I'll have a look. I might just have to make adjustments to the scss file. I'll let you know once I've figured.

**Comment by Queenen** [comment]
I've found a solution to the problem. Turns out that the _header.scss weren't imported inside the 
 <link href="/css/index.css" rel="stylesheet" /> which is linked in the index.html. Due to this the logo class weren't affected by the styling. I've deleted the inline styling and added the proper stylesheet to index.html.

**Comment by Olekrr** [comment]
Closing pull requests from sprint 1 as part of sprint 2 cleanup - contact me if you want it re-opened

**Pull request closed without merging**
