### PR TITLE
Fe listing listings

### PR DESCRIPTION
**Pull request by Gonlonge**
Made some improvements on search and filter

### CODE REVIEW

**Comment by akeek** [comment]
Nice work! But I have a couple of questions:
- Can you add som padding to the "View"-button so it's not glued to the corner?
- Can you add a couple of icons to the searchbar? For example a "filter"-icon for the dropdown-menu.

**Review by akeek — CHANGES_REQUESTED** [review]
Nice work! But I have a couple of questions:

- Can you add som padding to the "View"-button so it's not glued to the corner?
- Can you add a couple of icons to the searchbar? For example a "filter"-icon for the dropdown-menu.

**Comment by Gonlonge** [comment]
Hi, we are on it @akeek

**Review by akeek — COMMENTED** [review]
Awaiting updates before I do anything.

**Comment by akeek** [comment]
Approving now so the next dev can continue. Good job!

**Review by akeek — APPROVED** [review]

**Pull request merged**
