### PR TITLE
#513 Hamburger animations

### PR DESCRIPTION
**Pull request by YngvN**
Animations for hovering and when the nav is collapsed

### CODE REVIEW

**Comment by YngvN** [comment]
I might have done my own thing instead of using the Figma file :(

**Comment by AdrianMikk** [comment]
The burger is not showing up here. Please double-check the code

**Comment by YngvN** [comment]
It works when I click it. It should also just be on smaller screens

**Review by AdrianMikk — APPROVED** [review]
Hamburger menu is working and looks great. Job well done.

**Comment by AdrianMikk** [comment]
Would try to get it a bit more responsive, and not show on bigger devices.

**Pull request merged**
