### PR TITLE
Update box-shadow to neutral color

### PR DESCRIPTION
**Pull request by AndreasYager**
Updated register form box-shadow from green to grey

### CODE REVIEW

**Comment by kimrm** [comment]
I have tested, but unfortunately, I don't see the box-shadow color change from green to grey.

Since this project is using bootstrap and SASS, the color has to be changed in the custom scss files, not the index.css file (I dont think this file is actually in use). Bootstrap has a custom variable, $input-focus-box-shadow, for the focus box-shadow on the form-control class. I recommend adding this variable to /scr/scss/custom/_themeColorVariables.scss and run `npm run build` to see the change.

**Review by kimrm — CHANGES_REQUESTED** [review]
Check out previous comment.

**Comment by AndreasYager** [comment]
Hi @kimrm , 
Thanks for a thorough explanation. Based off your input, I believe I have made the necessary changes now. Let me know!

**Review by kimrm — APPROVED** [review]
Tested and looks good to me. Good job!

**Pull request merged**
