### PR TITLE
Cards on listings page

### PR DESCRIPTION
**Pull request by Eirik-Haukeland**
what has been done:
- changed id on the body element in [pages/listings/index.html](https://github.com/NoroffFEU/agency.noroff.dev/blob/main/pages/listings/index.html#L15) so that the [ruter in index.js](https://github.com/NoroffFEU/agency.noroff.dev/blob/main/index.js#L52-L55) recognises the page propely
- limited the lines in description and added ellipsis when to long
- bold-ed the title and added ellipsis then to log so we don't get multi line tittles
- added example of Applications and date field
- adjusted a lot of margins and padding's on the cards and there container
- made the container for search and result elements a flex container for easier styling
- added some break points

screen shot from my computer
image

### CODE REVIEW

**Review by MagnusPladsen — CHANGES_REQUESTED** [review]
One question i have is why the ID should be "listing" and not "listings" as its on the main branch? This seems to change the design when i changed it to "listings". I saw that it was wrong on this branch with "homePage", but i believe the main branch is the correct here with "listings"

**Comment by Eirik-Haukeland** [comment]
it used to be that the id was "homePage", and the option available in index.js was just "listing", but there as been an update in the repo yesterday. strangly they semm to have added two new cases that do the same if you se below 
adding of more cases: image
link to code in image: https://github.com/NoroffFEU/agency.noroff.dev/pull/298/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L52-R70

there change in the id: image
link to code in image: https://github.com/NoroffFEU/agency.noroff.dev/pull/298/files#diff-ed37031fbea750f473d8420060eb1d4cb5d4197e8a9dcc2f3cb2ed0e62f02e3b

**Comment by Eirik-Haukeland** [comment]
i notice now that there is a difference in that there new ones uses showListings and not renderListings as what i have been using. we might need to talk with the higherups to if there is conflict about witch file we are to run on this page

**Comment by MagnusPladsen** [comment]
I see that the showListings() function is for the admin view, so you are correct here with using id as "listing". 

The showListings() should be renamed and the ID should be changed so its not confusing. This should be done on another branch. 

I think this PR then is OK

**Review by MagnusPladsen — APPROVED** [review]

**Pull request merged**
