### PR TITLE
add e2e tests to pipeline

### PR DESCRIPTION
**Pull request by kyrregjerstad**
## Title
Parent ticket: [E2E testing v1](https://github.com/NoroffFEU/agency.noroff.dev/issues/777)

## Describe your changes:
I've updated the GitHub Actions workflow to include end-to-end (E2E) tests using Cypress. These tests focus on various aspects of the application, including login functionality and navigation. Additionally, I've added Cypress environment variables for test credentials and implemented a custom Cypress `login` command to streamline the login process across different test suites. Deleted redundant test files (`header-change.cy.js` and `home.cy.js`) and updated existing tests (`login.cy.js` and `active-links.cy.js`) to reflect these changes.

## Type of changes:
- GitHub workflow update
- Cypress configuration update
- Test file modifications and deletions
- Updated Cypress to latest version

## Checklist before requesting a review
* [x] I created a new branch before starting with this ticket?
* [x] I commented the issue after finish in the Frontend Team Board?
* [x] I moved the card to Quality Assurance after finish?

## Did you run into any issues?
- Yes, I encountered issues.
  - The `@testing-library/cypress` had been removed by another PR, so it had to be enabled again
  - Merged the `active-links.cy.js` into `login.cy.js` since they covered the same tests

## Feedback
- Yes please

### CODE REVIEW

**Review by Spookyrumble — APPROVED** [review]
LGTM

**Comment by Spookyrumble** [comment]
Just a heads up. This don't seem to be connected to an issue/ticket

**Comment by kyrregjerstad** [comment]
Hi @sulenchy ! 👋 Could you please include the E2E test in the required checks as well?

**Review by AnaCascante — APPROVED** [review]
LGTM

**Pull request merged**
