### PR TITLE
Made views for logged in student and logged in organisation

### PR DESCRIPTION
**Pull request by Jonast96**
The button links are empty so i have not added data attributes. Not sure where the login is gonna store infomation on who is logged in, so i have temporary consts with true||false where you can check how it will function. 

Please go over the JSdocs and see if everything makes sense.

### CODE REVIEW

**Comment by Christonn93** [comment]
@Jonast96
You need to update your work branch from your team branch, if the team branch is not updated you can request a merge from main.

This should resolve the conflict you are having. We can't approve the request before the conflict have been resolves.

**Comment by Jonast96** [comment]
> @Jonast96 You need to update your work branch from your team branch, if the team branch is not updated you can request a merge from main.
> 
> This should resolve the conflict you are having. We can't approve the request before the conflict have been resolves.

Should be fixed now.

**Comment by Christonn93** [comment]
Not sure what the conflict here is.

**Comment by Fermain** [comment]
Not sure either but I fixed it

**Pull request merged**
