### PR TITLE
found out why logout button not appearing after logged in

### PR DESCRIPTION
**Pull request by nyolarraklay**

### CODE REVIEW

**Review by Sovak3441 — CHANGES_REQUESTED** [review]
Please remove the console.log in index.js ln; 54.

**Comment by Sovak3441** [comment]
Please consider using createElement on line 57 (index.js) instead of innerHtml, as innerHtml is considered a security risk.

**Comment by nyolarraklay** [comment]
done Mr. QA

**Comment by Olekrr** [comment]
Closing pull requests from sprint 1 as part of sprint 2 cleanup - contact me if you want it re-opened

**Pull request closed without merging**
