### PR TITLE
Pages/TBD/offer-views changes

### PR DESCRIPTION
**Pull request by dvergnir**
- Reworked HTML for semantics
- added fw-bold after Figma wireframe
- added grey background to match other pages
- fixed a line made from hyphens wrapped in h2, now a horizontal rule
- left-oriented text instead of centered after Figma wireframe

### CODE REVIEW

**Comment by roxannefranco** [comment]
Looks ok to me :+1:

**Comment by martinthoresen** [comment]
Good job with reworking the page, it looks much better. The only thing i can commenton is the "Reject Application" button which has a very weak contrast and is quite hard to see. @dvergnir

**Comment by dvergnir** [comment]
> Good job with reworking the page, it looks much better. The only thing i can comment on is the "Reject Application" button which has a very weak contrast and is quite hard to see. @dvergnir

Yep. I did not touch the buttons as we are waiting for Design, and a button standard for all pages. Thanks for the feedback!

**Comment by martinthoresen** [comment]
Merging since task has been finished.

**Pull request merged**
