### PR TITLE
593 home page for applicants content does not change after login

### PR DESCRIPTION
**Pull request by maleneivy**
## Home/Frontpage content for logged in applicationUsers
593

## Describe your changes: 
In this PR I have added home.js in the js folder, that is connected to the index.html. 
I have written a function that shows content on the homepage/frontpage when a user is logged in as an applicant and if a user is not logged in.

## Type of changes:
- Created new js file in js folder: home.js
- Created new folder in js views,  named home with js file userViews.js. 
- Made changes to the viewListingsButton after changes in storage (that I did not make).

## Did you run into any issues?
- Yes, I ran into issues when someone changed the storage.js, but then I changed my code again to work with that new codechange. 

## Screenshots:
- Yes, the screenshots are included in the table below.
Before: 
Skjermbilde 2024-01-11 kl  14 32 45

After: 
Skjermbilde 2024-01-11 kl  14 33 32

## Additional information:
The View application button does not link anywhere.

## Feedback
- Yes, I want feedback.

### CODE REVIEW

**Comment by Olekrr** [comment]
Closing pull requests from sprint 1 as part of sprint 2 cleanup - contact me if you want it re-opened

**Comment by AdrianMikk** [comment]
[celebrate]     Adrian Mikkelsen Johannessen reacted to your message:
________________________________

**Comment by AdrianMikk** [comment]
Thank you @Olekrr. But I think my job is to close it, just so you know :D

**Comment by Olekrr** [comment]
@AdrianMikk 
Yeah sorry about that ^^
For some clarity - I was taked to look at other PR's since I had none up for review. Going through all the PR's that were up I noticed most were either:

1. Tiny changes with unresolved merge conflicts
2. changes to a section that that team no longer worked on 
3. contained merge conflicts that could delete large portions of code if not resolved in a proper manner.

As a result, me and my scrum master decided to close all pull requests from sprint 1 and earlier. There might be some collateral, but a PR can always be re-marked as open if a mistake happened in the "purge" :)

**Pull request closed without merging**
