### PR TITLE
Update terms_of_use.html

### PR DESCRIPTION
**Pull request by Christelmarita**
Deleted redundant "Back" button at the top of the page. "Back" button on bottom remains.

### CODE REVIEW

**Comment by Christelmarita** [comment]
I only deleted the button. have no idea why so many changes?

**Comment by KevinHavn** [comment]
File changes are most likely due to prettier, looks completely fine to me 👍

**Review by KevinHavn — APPROVED** [review]
LGTM

**Comment by Christelmarita** [comment]
I see now that it´s all formatting changes, except for the removed button. So I believe it´s all good. If you agree, please merge.

**Pull request merged**
