### PR TITLE
pathcing index page

### PR DESCRIPTION
**Pull request by Christonn93**

### CODE REVIEW

**Comment by Christonn93** [comment]
Current index: 
image

patch index: 
image

Some code changes to make the layout more correct

**Review by Pjatte1337 — APPROVED** [review]

**Review by Fermain — APPROVED** [review]

**Comment by Christonn93** [comment]
Looks like its fixed. Can you have a look also @Fermain ?

**Comment by Fermain** [comment]
Looks good to me

**Comment by Christonn93** [comment]
I will leave this open if something goes wrong. 
Dont merge and dont close yet.

**Comment by Christonn93** [comment]
Noting wrong. Just my head that is working on monday brain on a friday

**Pull request closed without merging**
