### PR TITLE
log-in function revert to original state

### PR DESCRIPTION
**Pull request by nyolarraklay**
## Describe your changes: 

Skjermbilde 2024-01-12 001755

I made some changes to the log-in function while resolving conflicts, I think I have erased or moved some codes. Reverting the codes from the original state.

## Type of changes:

Revert log-in function to its original code

## Checklist before requesting a review

* [* ] I created a new branch before starting with this ticket?
* [* ] I commented the issue after finish in the Frontend Team Board?
* [* ] I moved the card to Quality Assurance after finish?

## Did you run into any issues?

- Yes, I encountered issues. (Please describe below).

- while fixing this issue, I noticed that styling was not working in the local, not in vite. Found out that build in package.json is set to  "vite build"
- 
- Skjermbilde 2024-01-12 001706

## Additional information:

I need to change build to its original code to be able to test If my code is working
Skjermbilde 2024-01-12 002426

## Feedback

- Yes, I want feedback.

### CODE REVIEW

**Comment by Spookyrumble** [comment]
Vite has been configurd. If you are using local server it won't work. You now have to use vite with ``npm run dev`` and using the vite server linked in terminal after running this script! DO NOT revert package.json. This will break vite and deploy (static.yml)

**Review by Spookyrumble — CHANGES_REQUESTED** [review]
This looks to be a case of using live server on a vite build. 
The stylesheets are linked in index.js. There is no need for them in the HTML files.
Vite handles the build so adding sass back to scripts in package will break vite build and deployment.
The login function revert I can't really review. I removed it as part of the conflict I had when my branch was old and there was new changes merged from main so I left those alone and removed mine.

**Comment by nyolarraklay** [comment]
ok done. reverting package.json
sorry

**Review by Spookyrumble — CHANGES_REQUESTED** [review]
Please remove stylesheet links from the html files. They are not needed. style is imported to index.js and Vite applies it.

**Review by Spookyrumble — APPROVED** [review]
LGTM

**Comment by Spookyrumble** [comment]
I would like Mathias to also have a look and make sure they don't have colliding changes in these files.

**Comment by MHerholdt94** [comment]
> I would like Mathias to also have a look and make sure they don't have colliding changes in these files.

LGTM 😋 This PR includes all changes that is in my PR and more, so my PR regarding the error can be closed and this one merged

**Review by MHerholdt94 — APPROVED** [review]
LGTM 😋 This PR includes all changes that is in my PR as well

**Pull request merged**
