### PR TITLE
mb-5 added to listingContainer

### PR DESCRIPTION
**Pull request by Christelmarita**
mb-5 added to listingContainer to create space between listings and footer

### CODE REVIEW

**Review by KevinHavn — APPROVED** [review]
Looks good to me! 
package-lock.json changes looks weird though, but I'm not too sure how exactly that works.

**Comment by Christelmarita** [comment]
@KevinHavn should we not merge the package lock then? How do we only merge the listings index?

**Comment by Christelmarita** [comment]
@KevinHavn I´ve updated the package lock to be equal to main branch. Will you have a look again?

**Comment by KevinHavn** [comment]
> @KevinHavn should we not merge the package lock then? How do we only merge the listings index?

Honestly not sure. The way I see other people do it is that they only commit the files they directly change.
The method I use to choose which files are commited is the VSCode source control.

**Pull request merged**
