### PR TITLE
created sort functions and fetch api in the listings page

### PR DESCRIPTION
**Pull request by nyolarraklay**

### CODE REVIEW

**Comment by Sovak3441** [comment]
Please resolve the Merge Conflict in index.html and renderListings.js. See screen shots below.

Skjermbilde 2024-01-09 kl  15 36 57
Skjermbilde 2024-01-09 kl  15 37 33

**Comment by nyolarraklay** [comment]
done

**Comment by Olekrr** [comment]
I would suggest closing this PR without a merge - currently my group is working on the listings page for sprint 2 and have done major rehauls to its structure.

**Comment by Olekrr** [comment]
Closing pull requests from sprint 1 as part of sprint 2 cleanup - contact me if you want it re-opened

**Pull request closed without merging**
